import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

// /*
// Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
// Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// */


ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
